"""Initialize database schema from models

Revision ID: 6bed3f5bfd12
Revises: e2f7c584dc50
Create Date: 2026-07-15 17:09:55.939221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bed3f5bfd12'
down_revision: Union[str, Sequence[str], None] = 'e2f7c584dc50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
